apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-crm-service-customers
spec:
  selector:
    matchLabels:
      app: bookstore-crm-service-customers
  replicas: 2
  template:
    metadata:
      labels:
        app: bookstore-crm-service-customers
    spec:
      containers:
        - name: bookstore-crm-service-customers
          image: soobinrho/17647-bookstore-crm-service-customers:latest
          imagePullPolicy: Always
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - bookstore-crm-service-customers
