apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-api-service-customers
  namespace: bookstore-ns
spec:
  selector:
    matchLabels:
      app: bookstore-api-service-customers
  replicas: 2
  template:
    metadata:
      labels:
        app: bookstore-api-service-customers
    spec:
      containers:
        - name: bookstore-api-service-customers
          image: soobinrho/17647-bookstore-api-service-customers:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
          stdin: true
          envFrom:
            - secretRef:
                name: secrets-api-service-customers
          # [DEBUG] Disabling livenessprobe until the infinite error crash loop gets resolved.
          # livenessProbe:
          #   httpGet:
          #     path: /status
          #     port: 3000
          #   initialDelaySeconds: 600
          #   periodSeconds: 30
          #   failureThreshold: 3
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - bookstore-api-service-customers
                      - bookstore-api-service-books
