apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-bff-mobile
  namespace: bookstore-ns
spec:
  selector:
    matchLabels:
      app: bookstore-bff-mobile
  replicas: 2
  template:
    metadata:
      labels:
        app: bookstore-bff-mobile
    spec:
      containers:
        - name: bookstore-bff-mobile
          image: soobinrho/17647-bookstore-bff-mobile:latest
          imagePullPolicy: Always
          terminationMessagePath: "/tmp/k8s_termination_message.log"
          ports:
          - containerPort: 80
          startupProbe:
            httpGet:
              path: /status
              port: 80
            periodSeconds: 5
            failureThreshold: 70
          livenessProbe:
            httpGet:
              path: /status
              port: 80
            periodSeconds: 30
            failureThreshold: 3
