apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-crm-service-customers
spec:
  selector:
    matchLabels:
      app: bookstore-crm-service-customers
  replicas: 2
  template:
    metadata:
      labels:
        app: bookstore-crm-service-customers
    spec:
      containers:
        - name: bookstore-crm-service-customers
          image: soobinrho/17647-bookstore-crm-service-customers:latest
          imagePullPolicy: Always
          terminationMessagePath: "/tmp/k8s_termination_message.log"
          ports:
          - containerPort: 587
          envFrom:
            - secretRef:
                name: secrets-crm-service-customers
