apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-bff-mobile
spec:
  selector:
    matchLabels:
      run: bookstore-bff-mobile
  replicas: 2
  template:
    metadata:
      labels:
        run: bookstore-bff-mobile
    spec:
      containers:
      - name: bookstore-bff-mobile
        image: soobinrho/17647-bookstore-bff-mobile:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: prod-secrets
