#!/bin/bash

PATH_DOT_ENV='../.env'
DOT_ENV_API_SERVICE_BOOKS_COMMANDS='.env.api-service-books-commands'
DOT_ENV_API_SERVICE_BOOKS_QUERIES='.env.api-service-books-queries'
DOT_ENV_API_SERVICE_CUSTOMERS='.env.api-service-customers'
DOT_ENV_CRM_SERVICE_CUSTOMERS='.env.crm-service-customers'

# ==========================
# api-service-books-commands
# ==========================
grep '^DB_BOOKS_COMMANDS_URL=' ${PATH_DOT_ENV} >${DOT_ENV_API_SERVICE_BOOKS_COMMANDS}
grep '^DB_BOOKS_COMMANDS_PORT=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_BOOKS_COMMANDS}
grep '^DB_BOOKS_COMMANDS_USER=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_BOOKS_COMMANDS}
grep '^DB_BOOKS_COMMANDS_PASS=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_BOOKS_COMMANDS}
grep '^DB_BOOKS_COMMANDS_DATABASE=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_BOOKS_COMMANDS}
sed --in-place 's/DB_BOOKS_COMMANDS_/DB_/g' ${DOT_ENV_API_SERVICE_BOOKS_COMMANDS}
grep '^GEMINI_API_KEY=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_BOOKS_COMMANDS}

# =========================
# api-service-books-queries
# =========================
grep '^DB_BOOKS_QUERIES_URL=' ${PATH_DOT_ENV} >${DOT_ENV_API_SERVICE_BOOKS_QUERIES}
grep '^DB_BOOKS_QUERIES_USER=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_BOOKS_QUERIES}
grep '^DB_BOOKS_QUERIES_PASS=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_BOOKS_QUERIES}
grep '^DB_BOOKS_QUERIES_DATABASE=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_BOOKS_QUERIES}
grep '^DB_BOOKS_QUERIES_COLLECTION=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_BOOKS_QUERIES}
sed --in-place 's/DB_BOOKS_QUERIES_/DB_/g' ${DOT_ENV_API_SERVICE_BOOKS_QUERIES}
grep '^API_RELATED_BOOKS_URL_PROD=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_BOOKS_QUERIES}
sed --in-place 's/API_RELATED_BOOKS_URL_PROD/API_RELATED_BOOKS_URL/g' ${DOT_ENV_API_SERVICE_BOOKS_QUERIES}

# =====================
# api-service-customers
# =====================
grep '^DB_CUSTOMERS_URL=' ${PATH_DOT_ENV} >${DOT_ENV_API_SERVICE_CUSTOMERS}
grep '^DB_CUSTOMERS_PORT=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_CUSTOMERS}
grep '^DB_CUSTOMERS_USER=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_CUSTOMERS}
grep '^DB_CUSTOMERS_PASS=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_CUSTOMERS}
grep '^DB_CUSTOMERS_DATABASE=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_CUSTOMERS}
sed --in-place 's/DB_CUSTOMERS_/DB_/g' ${DOT_ENV_API_SERVICE_CUSTOMERS}
grep '^KAFKA_TOPIC=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_CUSTOMERS}
grep '^KAFKA_BROKER_0_URL=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_CUSTOMERS}
grep '^KAFKA_BROKER_1_URL=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_CUSTOMERS}
grep '^KAFKA_BROKER_2_URL=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_CUSTOMERS}

# =====================
# crm-service-customers
# =====================
grep '^KAFKA_TOPIC=' ${PATH_DOT_ENV} >${DOT_ENV_CRM_SERVICE_CUSTOMERS}
grep '^KAFKA_BROKER_0_URL=' ${PATH_DOT_ENV} >>${DOT_ENV_CRM_SERVICE_CUSTOMERS}
grep '^KAFKA_BROKER_1_URL=' ${PATH_DOT_ENV} >>${DOT_ENV_CRM_SERVICE_CUSTOMERS}
grep '^KAFKA_BROKER_2_URL=' ${PATH_DOT_ENV} >>${DOT_ENV_CRM_SERVICE_CUSTOMERS}
grep '^SMTP_SERVER_URL=' ${PATH_DOT_ENV} >>${DOT_ENV_CRM_SERVICE_CUSTOMERS}
grep '^SMTP_SERVER_PORT=' ${PATH_DOT_ENV} >>${DOT_ENV_CRM_SERVICE_CUSTOMERS}
grep '^SMTP_SERVER_ID=' ${PATH_DOT_ENV} >>${DOT_ENV_CRM_SERVICE_CUSTOMERS}
grep '^SMTP_SERVER_PASS=' ${PATH_DOT_ENV} >>${DOT_ENV_CRM_SERVICE_CUSTOMERS}
