#!/bin/bash

PATH_DOT_ENV='../.env'
DOT_ENV_API_SERVICE_BOOKS='.env.api-service-books'
DOT_ENV_API_SERVICE_CUSTOMERS='.env.api-service-customers'
DOT_ENV_CRM_SERVICE_CUSTOMERS='.env.crm-service-customers'

# =================
# api-service-books
# =================
grep '^DB_URL=' ${PATH_DOT_ENV} >${DOT_ENV_API_SERVICE_BOOKS}
grep '^DB_PORT=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_BOOKS}
grep '^DB_BOOKS_USER=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_BOOKS}
grep '^DB_BOOKS_PASS=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_BOOKS}
grep '^DB_BOOKS_DATABASE=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_BOOKS}
sed --in-place 's/DB_BOOKS_/DB_/g' ${DOT_ENV_API_SERVICE_BOOKS}
grep '^GEMINI_API_KEY=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_BOOKS}
grep '^API_RELATED_BOOKS_URL_PROD=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_BOOKS}
sed --in-place 's/API_RELATED_BOOKS_URL_PROD/API_RELATED_BOOKS_URL/g' ${DOT_ENV_API_SERVICE_BOOKS}

# =====================
# api-service-customers
# =====================
grep '^DB_URL=' ${PATH_DOT_ENV} >${DOT_ENV_API_SERVICE_CUSTOMERS}
grep '^DB_PORT=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_CUSTOMERS}
grep '^DB_CUSTOMERS_USER=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_CUSTOMERS}
grep '^DB_CUSTOMERS_PASS=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_CUSTOMERS}
grep '^DB_CUSTOMERS_DATABASE=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_CUSTOMERS}
sed --in-place 's/DB_CUSTOMERS_/DB_/g' ${DOT_ENV_API_SERVICE_CUSTOMERS}
grep '^KAFKA_TOPIC=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_CUSTOMERS}
grep '^KAFKA_BROKER_0_URL=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_CUSTOMERS}
grep '^KAFKA_BROKER_1_URL=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_CUSTOMERS}
grep '^KAFKA_BROKER_2_URL=' ${PATH_DOT_ENV} >>${DOT_ENV_API_SERVICE_CUSTOMERS}

# =====================
# crm-service-customers
# =====================
grep '^KAFKA_TOPIC=' ${PATH_DOT_ENV} >${DOT_ENV_CRM_SERVICE_CUSTOMERS}
grep '^KAFKA_BROKER_0_URL=' ${PATH_DOT_ENV} >>${DOT_ENV_CRM_SERVICE_CUSTOMERS}
grep '^KAFKA_BROKER_1_URL=' ${PATH_DOT_ENV} >>${DOT_ENV_CRM_SERVICE_CUSTOMERS}
grep '^KAFKA_BROKER_2_URL=' ${PATH_DOT_ENV} >>${DOT_ENV_CRM_SERVICE_CUSTOMERS}
grep '^SMTP_SERVER_URL=' ${PATH_DOT_ENV} >>${DOT_ENV_CRM_SERVICE_CUSTOMERS}
grep '^SMTP_SERVER_PORT=' ${PATH_DOT_ENV} >>${DOT_ENV_CRM_SERVICE_CUSTOMERS}
grep '^SMTP_SERVER_ID=' ${PATH_DOT_ENV} >>${DOT_ENV_CRM_SERVICE_CUSTOMERS}
grep '^SMTP_SERVER_PASS=' ${PATH_DOT_ENV} >>${DOT_ENV_CRM_SERVICE_CUSTOMERS}
