apiVersion: v1
kind: Service
metadata:
  name: lb-bookstore-bff-mobile
  namespace: bookstore-ns
spec:
  type: LoadBalancer
  selector:
    app: bookstore-bff-mobile
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
