apiVersion: v1
kind: Service
metadata:
  name: bookstore-bff-mobile
  namespace: bookstore-ns
spec:
  type: LoadBalancer
  selector:
    app: bookstore-bff-mobile
  ports:
    - port: 80
      targetPort: 80
