apiVersion: v1
kind: Service
metadata:
  name: bookstore-crm-service-customers
  namespace: bookstore-ns
  labels:
    app: bookstore-crm-service-customers
spec:
  ports:
  - port: 587
    targetport: 587
    protocol: TCP
  selector:
    app: bookstore-crm-service-customers
