apiVersion: v1
kind: Service
metadata:
  name: bookstore-api-service-books
  namespace: bookstore-ns
  labels:
    app: bookstore-api-service-books
spec:
  ports:
  - port: 3000
  selector:
    app: bookstore-api-service-books
