apiVersion: v1
kind: Service
metadata:
  name: bookstore-api-service-customers
  labels:
    run: bookstore-api-service-customers
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    run: bookstore-api-service-customers
