apiVersion: v1
kind: Service
metadata:
  name: bookstore-api-service-customers
  namespace: bookstore-ns
  labels:
    app: bookstore-api-service-customers
spec:
  ports:
  - port: 3000
    targetport: 3000
    protocol: TCP
  selector:
    app: bookstore-api-service-customers
